lucee52:
  build: ./5.2
  ports: 
   - "8052:8888"
  #volumes:
    # - /workbench/lucee-dockerfiles/5.2/lucee-server.xml:/opt/lucee/server/lucee-server/context/lucee-server.xml
    # - /workbench/lucee-dockerfiles/5.2/lucee-web.xml:/opt/lucee/web/lucee-web.xml.cfm
lucee52-slim:
  build: ./5.2-slim
  ports:
   - "8152:8888"
  #volumes:
    # - /workbench/lucee-dockerfiles/5.2/lucee-server.xml:/opt/lucee/server/lucee-server/context/lucee-server.xml
    # - /workbench/lucee-dockerfiles/5.2/lucee-web.xml:/opt/lucee/web/lucee-web.xml.cfm
lucee52-alpine:
  build: ./5.2-alpine
  ports:
   - "8252:8888"
  #volumes:
    # - /workbench/lucee-dockerfiles/5.2/lucee-server.xml:/opt/lucee/server/lucee-server/context/lucee-server.xml
    # - /workbench/lucee-dockerfiles/5.2/lucee-web.xml:/opt/lucee/web/lucee-web.xml.cfm

lucee52-nginx:
  build: ./lucee-nginx/5.2
  environment:
    - "VIRTUAL_HOST=lucee52-nginx.*"
  #volumes:
    # - /workbench/lucee-dockerfiles/lucee-nginx/5.2/lucee-server.xml:/opt/lucee/server/lucee-server/context/lucee-server.xml
    # - /workbench/lucee-dockerfiles/lucee-nginx/5.2/lucee-web.xml:/opt/lucee/web/lucee-web.xml.cfm
lucee52-nginx-slim:
  build: ./lucee-nginx/5.2-slim
  environment:
    - "VIRTUAL_HOST=lucee52-nginx-slim.*"
  #volumes:
    # - /workbench/lucee-dockerfiles/lucee-nginx/5.2/lucee-server.xml:/opt/lucee/server/lucee-server/context/lucee-server.xml
    # - /workbench/lucee-dockerfiles/lucee-nginx/5.2/lucee-web.xml:/opt/lucee/web/lucee-web.xml.cfm
