lucee52:
  build: ./5.2
  ports: 
   - "8052:8888"
  #volumes:
    # - /workbench/lucee-dockerfiles/5.2/lucee-server.xml:/opt/lucee/server/lucee-server/context/lucee-server.xml
    # - /workbench/lucee-dockerfiles/5.2/lucee-web.xml:/opt/lucee/web/lucee-web.xml.cfm
lucee52-slim:
  build: ./5.2-slim
  ports:
   - "8152:8888"
  #volumes:
    # - /workbench/lucee-dockerfiles/5.2/lucee-server.xml:/opt/lucee/server/lucee-server/context/lucee-server.xml
    # - /workbench/lucee-dockerfiles/5.2/lucee-web.xml:/opt/lucee/web/lucee-web.xml.cfm
lucee51:
  build: ./5.1
  ports: 
   - "8051:8888"
  #volumes:
    # - /workbench/lucee-dockerfiles/5.1/lucee-server.xml:/opt/lucee/server/lucee-server/context/lucee-server.xml
    # - /workbench/lucee-dockerfiles/5.1/lucee-web.xml:/opt/lucee/web/lucee-web.xml.cfm
lucee50:
  build: ./5.0
  ports: 
   - "8050:8888"
  #volumes:
    # - /workbench/lucee-dockerfiles/5.0/lucee-server.xml:/opt/lucee/server/lucee-server/context/lucee-server.xml
    # - /workbench/lucee-dockerfiles/5.0/lucee-web.xml:/opt/lucee/web/lucee-web.xml.cfm
lucee45:
  build: ./4.5
  ports: 
   - "8045:8888"
  #volumes:
    # - /workbench/lucee-dockerfiles/4.5/lucee-server.xml:/opt/lucee/server/lucee-server/context/lucee-server.xml
    # - /workbench/lucee-dockerfiles/4.5/lucee-web.xml:/opt/lucee/web/lucee-web.xml.cfm

lucee52-nginx:
  build: ./lucee-nginx/5.2
  environment:
    - "VIRTUAL_HOST=lucee52-nginx.*"
  #volumes:
    # - /workbench/lucee-dockerfiles/lucee-nginx/5.2/lucee-server.xml:/opt/lucee/server/lucee-server/context/lucee-server.xml
    # - /workbench/lucee-dockerfiles/lucee-nginx/5.2/lucee-web.xml:/opt/lucee/web/lucee-web.xml.cfm
lucee51-nginx:
  build: ./lucee-nginx/5.1
  environment:
    - "VIRTUAL_HOST=lucee51-nginx.*"
  #volumes:
    # - /workbench/lucee-dockerfiles/lucee-nginx/5.1/lucee-server.xml:/opt/lucee/server/lucee-server/context/lucee-server.xml
    # - /workbench/lucee-dockerfiles/lucee-nginx/5.1/lucee-web.xml:/opt/lucee/web/lucee-web.xml.cfm
lucee50-nginx:
  build: ./lucee-nginx/5.0
  environment:
    - "VIRTUAL_HOST=lucee50-nginx.*"
  #volumes:
    # - /workbench/lucee-dockerfiles/lucee-nginx/5.0/lucee-server.xml:/opt/lucee/server/lucee-server/context/lucee-server.xml
    # - /workbench/lucee-dockerfiles/lucee-nginx/5.0/lucee-web.xml:/opt/lucee/web/lucee-web.xml.cfm
lucee4-nginx:
  build: ./lucee-nginx/4.5
  environment:
    - "VIRTUAL_HOST=lucee4-nginx.*"
  #volumes:
    # - /workbench/lucee-dockerfiles/lucee-nginx/4.5/lucee-server.xml:/opt/lucee/server/lucee-server/context/lucee-server.xml
    # - /workbench/lucee-dockerfiles/lucee-nginx/4.5/lucee-web.xml:/opt/lucee/web/lucee-web.xml.cfm
